// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgK4UdIqvMLPP4HXntubtFY0KutY9Z0Qg',
    appId: '1:199318937184:web:ed6c2335be262a927bad05',
    messagingSenderId: '199318937184',
    projectId: 'strict-exam',
    authDomain: 'strict-exam.firebaseapp.com',
    storageBucket: 'strict-exam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuHo5uDWq-4wsCuUyQu2rgbgHUKcBBXyE',
    appId: '1:199318937184:android:a4611c11419990d47bad05',
    messagingSenderId: '199318937184',
    projectId: 'strict-exam',
    storageBucket: 'strict-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWnK4zn4x2A-1bkMGiRrwnRFi8NQtkgU',
    appId: '1:199318937184:ios:5227446428ce38ff7bad05',
    messagingSenderId: '199318937184',
    projectId: 'strict-exam',
    storageBucket: 'strict-exam.appspot.com',
    iosClientId: '199318937184-mg394ehik5ap1pmsuki6978ee4huoq4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.strictExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWnK4zn4x2A-1bkMGiRrwnRFi8NQtkgU',
    appId: '1:199318937184:ios:5227446428ce38ff7bad05',
    messagingSenderId: '199318937184',
    projectId: 'strict-exam',
    storageBucket: 'strict-exam.appspot.com',
    iosClientId: '199318937184-mg394ehik5ap1pmsuki6978ee4huoq4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.strictExam',
  );
}
